'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'lv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.courses': 'Courses',
    'nav.team': 'Our Team',
    'nav.contact': 'Contact',
    'hero.title': 'We create interactive digital products, AI workflows, and custom learning systems',
    'hero.subtitle': 'Transform your ideas into engaging digital experiences with our creative and technical expertise.',
    'hero.cta.consultation': 'Book a Free Consultation',
    'hero.cta.projects': 'See Our Projects',
    'whatwedo.title': 'What We Do',
    'whatwedo.interactive.title': 'Interactive Content Design',
    'whatwedo.interactive.desc': 'We craft engaging digital experiences including interactive books, catalogs, and multimedia content that captivates your audience.',
    'whatwedo.ai.title': 'AI Integrations & Agents',
    'whatwedo.ai.desc': 'Leverage cutting-edge AI technology to automate workflows, enhance productivity, and create intelligent systems tailored to your needs.',
    'whatwedo.education.title': 'Education Systems',
    'whatwedo.education.desc': 'Design and implement comprehensive learning management systems and instructional content that drives real results.',
    'whychooseus.title': 'Why Choose Us',
    'whychooseus.clientcentered': 'Client-Centered Approach',
    'whychooseus.creative': 'Creative Solutions',
    'whychooseus.results': 'Results-Driven',
    'whychooseus.ai': 'AI Expertise',
    'whychooseus.design': 'Modern Design',
    'whychooseus.educational': 'Educational Excellence',
    'featured.title': 'Featured Projects',
    'featured.viewall': 'View All Projects',
    'howwework.title': 'How We Work',
    'howwework.discovery': 'Discovery',
    'howwework.discovery.desc': 'We learn about your goals, challenges, and vision',
    'howwework.design': 'Design',
    'howwework.design.desc': 'Creating beautiful, user-centered solutions',
    'howwework.aiintegration': 'AI Integration',
    'howwework.aiintegration.desc': 'Implementing smart automation and workflows',
    'howwework.delivery': 'Delivery',
    'howwework.delivery.desc': 'Launching your project with comprehensive support',
    'howwework.support': 'Support',
    'howwework.support.desc': 'Ongoing maintenance and optimization',
    'testimonials.title': 'What Our Clients Say',
    'cta.title': 'Ready to Transform Your Ideas?',
    'cta.subtitle': 'Start your free consultation today and discover how we can help you achieve your goals.',
    'cta.button': 'Book Your Free Consultation',
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the talented professionals behind E9 Studija.',
    'team.whoweare': 'Who We Are',
    'team.description1': 'E9 Studija is a creative digital studio based in Latvia, specializing in interactive content design, AI integrations, and educational technology solutions.',
    'team.description2': 'Our team is passionate about innovation, collaboration, and delivering results that exceed expectations.',
    'team.description3': "Whether you're looking to create an interactive learning platform, integrate AI into your workflows, or design engaging digital content, we have the expertise to bring your vision to life.",
    'team.meetteam': 'Meet Our Team',
    'team.member1.name': 'Anna Kovaļevska',
    'team.member1.position': 'Founder & Creative Director',
    'team.member1.bio': 'With over 15 years of experience in digital design and education, Anna leads our creative vision and client strategy.',
    'team.member2.name': 'Māris Liepiņš',
    'team.member2.position': 'Lead AI Engineer',
    'team.member2.bio': 'Māris specializes in AI integrations and automation, bringing cutting-edge technology solutions to our clients.',
    'team.member3.name': 'Laura Bērziņa',
    'team.member3.position': 'UX/UI Designer',
    'team.member3.bio': 'Laura creates beautiful, intuitive interfaces that delight users and drive engagement across all platforms.',
    'team.member4.name': 'Jānis Kalniņš',
    'team.member4.position': 'Education Technology Specialist',
    'team.member4.bio': 'Jānis designs and implements comprehensive learning systems that transform educational experiences.',
    'team.worktogether': "Let's Work Together",
    'team.worktogether.subtitle': 'Ready to start your project? Get in touch with our team today.',
    'team.contactus': 'Contact Us',
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Ready to transform your ideas into reality? Book a free consultation or send us a message.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.name.placeholder': 'Your full name',
    'contact.email.placeholder': 'your@email.com',
    'contact.message.placeholder': 'Tell us about your project...',
    'contact.send': 'Submit',
    'contact.sending': 'Sending...',
    'contact.select.time': 'Select Time Slot',
    'contact.success.title': 'Message Sent!',
    'contact.success.message': 'Your form was submitted, we will contact you!',
    'contact.error.fields': 'Please fill in all required fields',
    'contact.error.failed': 'Failed to submit form. Please try again.',
    'contact.no.slots': 'No available time slots. Please contact us directly.',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Hours',
    'contact.info.hours.text': 'Mon-Fri: 9AM - 6PM',
    'contact.info.response': 'Response Time',
    'contact.info.response.text': 'Within 24 hours',
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Explore our portfolio of innovative digital products, AI integrations, and learning systems.',
    'projects.loading': 'Loading...',
    'projects.view': 'View Project',
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Expand your skills with our expertly crafted online courses.',
    'courses.filter.all': 'All',
    'courses.filter.marketing': 'Marketing',
    'courses.filter.business': 'Business',
    'courses.filter.creativity': 'Creativity',
    'courses.filter.education': 'Education',
    'courses.filter.ai': 'AI Skills',
    'courses.filter.technology': 'Technology',
    'courses.filter.personal': 'Personal Development',
    'courses.custom.title': 'Custom Course Development',
    'courses.custom.subtitle': 'Need a custom learning solution for your organization? We design and develop tailored courses.',
    'courses.custom.button': 'Discuss Your Needs',
    'footer.description': 'Creative and AI consulting studio specializing in interactive digital products and custom learning systems.',
    'footer.quicklinks': 'Quick Links',
    'footer.connect': 'Connect With Us',
    'footer.rights': 'All rights reserved.',
    'project.back': 'Back to Projects',
    'project.client': 'Client',
    'project.category': 'Category',
    'project.overview': 'Overview',
    'project.goals': 'Project Goals',
    'project.process': 'Our Process',
    'project.features': 'Key Features',
    'project.results': 'Results',
    'project.cta.title': 'Ready to Start Your Project?',
    'project.cta.subtitle': "Let's discuss how we can bring your vision to life.",
    'project.cta.button': 'Get in Touch',
  },
  lv: {
    'nav.home': 'Sākums',
    'nav.projects': 'Projekti',
    'nav.courses': 'Kursi',
    'nav.team': 'Mūsu Komanda',
    'nav.contact': 'Kontakti',
    'hero.title': 'Mēs veidojam interaktīvus digitālus produktus, AI risinājumus un mācību sistēmas',
    'hero.subtitle': 'Pārveidojiet savas idejas saistošās digitālās pieredzēs ar mūsu radošo un tehnisko kompetenci.',
    'hero.cta.consultation': 'Rezervēt Bezmaksas Konsultāciju',
    'hero.cta.projects': 'Skatīt Mūsu Projektus',
    'whatwedo.title': 'Ko Mēs Darām',
    'whatwedo.interactive.title': 'Interaktīva Satura Dizains',
    'whatwedo.interactive.desc': 'Mēs veidojam saistošas digitālās pieredzes, tostarp interaktīvas grāmatas, katalogus un multimediju saturu.',
    'whatwedo.ai.title': 'AI Integrācijas un Aģenti',
    'whatwedo.ai.desc': 'Izmantojiet jaunāko AI tehnoloģiju, lai automatizētu darba procesus un izveidotu inteliģentas sistēmas.',
    'whatwedo.education.title': 'Izglītības Sistēmas',
    'whatwedo.education.desc': 'Projektējiet un ieviešiet visaptverošas mācību pārvaldības sistēmas un mācību saturu.',
    'whychooseus.title': 'Kāpēc Izvēlēties Mūs',
    'whychooseus.clientcentered': 'Klienta Centrēta Pieeja',
    'whychooseus.creative': 'Radoši Risinājumi',
    'whychooseus.results': 'Rezultātu Orientēti',
    'whychooseus.ai': 'AI Ekspertīze',
    'whychooseus.design': 'Moderns Dizains',
    'whychooseus.educational': 'Izglītības Izcilība',
    'featured.title': 'Izceltie Projekti',
    'featured.viewall': 'Skatīt Visus Projektus',
    'howwework.title': 'Kā Mēs Strādājam',
    'howwework.discovery': 'Izpēte',
    'howwework.discovery.desc': 'Mēs uzzinām par jūsu mērķiem, izaicinājumiem un redzējumu',
    'howwework.design': 'Dizains',
    'howwework.design.desc': 'Veidojam skaistu, lietotājam centrētu risinājumu',
    'howwework.aiintegration': 'AI Integrācija',
    'howwework.aiintegration.desc': 'Ieviešam inteliģentu automatizāciju un darba procesus',
    'howwework.delivery': 'Piegāde',
    'howwework.delivery.desc': 'Palaidām jūsu projektu ar visaptverošu atbalstu',
    'howwework.support': 'Atbalsts',
    'howwework.support.desc': 'Nepārtraukta uzturēšana un optimizācija',
    'testimonials.title': 'Ko Saka Mūsu Klienti',
    'cta.title': 'Gatavs Pārveidot Savas Idejas?',
    'cta.subtitle': 'Sāciet savu bezmaksas konsultāciju šodien.',
    'cta.button': 'Rezervēt Bezmaksas Konsultāciju',
    'team.title': 'Mūsu Komanda',
    'team.subtitle': 'Iepazīstieties ar talantīgajiem profesionāļiem E9 Studija pamatā.',
    'team.whoweare': 'Kas Mēs Esam',
    'team.description1': 'E9 Studija ir radoša digitālā studija Latvijā, kas specializējas interaktīvā satura dizainā, AI integrācijās un izglītības tehnoloģiju risinājumos.',
    'team.description2': 'Mūsu komanda ir aizrautīga ar inovācijām, sadarbību un rezultātu sniegšanu.',
    'team.description3': 'Neatkarīgi no tā, vai vēlaties izveidot interaktīvu mācību platformu vai integrēt AI savos darba procesos, mēs esam šeit.',
    'team.meetteam': 'Iepazīstieties ar Mūsu Komandu',
    'team.member1.name': 'Anna Kovaļevska',
    'team.member1.position': 'Dibinātāja un Radošā Direktore',
    'team.member1.bio': 'Ar vairāk nekā 15 gadu pieredzi digitālajā dizainā un izglītībā, Anna vada mūsu radošo vīziju.',
    'team.member2.name': 'Māris Liepiņš',
    'team.member2.position': 'Galvenais AI Inženieris',
    'team.member2.bio': 'Māris specializējas AI integrācijās un automatizācijā.',
    'team.member3.name': 'Laura Bērziņa',
    'team.member3.position': 'UX/UI Dizainere',
    'team.member3.bio': 'Laura rada skaistu, intuitīvu saskarni.',
    'team.member4.name': 'Jānis Kalniņš',
    'team.member4.position': 'Izglītības Tehnoloģiju Speciālists',
    'team.member4.bio': 'Jānis projektē un ievieš visaptverošas mācību sistēmas.',
    'team.worktogether': 'Strādāsim Kopā',
    'team.worktogether.subtitle': 'Gatavs sākt savu projektu? Sazinieties ar mūsu komandu.',
    'team.contactus': 'Sazināties ar Mums',
    'contact.title': 'Sazinies ar Mums',
    'contact.subtitle': 'Gatavs pārveidot savas idejas realitātē? Rezervē bezmaksas konsultāciju.',
    'contact.name': 'Vārds',
    'contact.email': 'E-pasts',
    'contact.message': 'Ziņojums',
    'contact.name.placeholder': 'Tavs pilnais vārds',
    'contact.email.placeholder': 'tavs@epasts.lv',
    'contact.message.placeholder': 'Pastāsti mums par savu projektu...',
    'contact.send': 'Iesniegt',
    'contact.sending': 'Sūta...',
    'contact.select.time': 'Izvēlies Laiku',
    'contact.success.title': 'Ziņa Nosūtīta!',
    'contact.success.message': 'Paldies, anketa ir iesniegta! Mēs ar jums sazināsimies!',
    'contact.error.fields': 'Lūdzu, aizpildi visus obligātos laukus',
    'contact.error.failed': 'Neizdevās nosūtīt formu. Lūdzu, mēģini vēlreiz.',
    'contact.no.slots': 'Pašlaik nav pieejamu laika slotu.',
    'contact.info.email': 'E-pasts',
    'contact.info.hours': 'Darba Laiks',
    'contact.info.hours.text': 'P-Pk: 9:00 - 18:00',
    'contact.info.response': 'Atbildes Laiks',
    'contact.info.response.text': 'Līdz 24 stundām',
    'projects.title': 'Mūsu Projekti',
    'projects.subtitle': 'Iepazīstieties ar mūsu inovatīvu digitālo produktu portfeli.',
    'projects.loading': 'Ielādē...',
    'projects.view': 'Skatīt Projektu',
    'courses.title': 'Mūsu Kursi',
    'courses.subtitle': 'Paplašiniet savas prasmes ar mūsu ekspertu veidotajiem tiešsaistes kursiem.',
    'courses.filter.all': 'Visi',
    'courses.filter.marketing': 'Mārketings',
    'courses.filter.business': 'Bizness',
    'courses.filter.creativity': 'Radošums',
    'courses.filter.education': 'Izglītība',
    'courses.filter.ai': 'AI Prasmes',
    'courses.filter.technology': 'Tehnoloģijas',
    'courses.filter.personal': 'Personīga Izaugsme',
    'courses.custom.title': 'Individuālu Kursu Izstrāde',
    'courses.custom.subtitle': 'Vai jums nepieciešams individuāls mācību risinājums?',
    'courses.custom.button': 'Apspriežam Jūsu Vajadzības',
    'footer.description': 'Radošā un AI konsultēšanas studija, kas specializējas interaktīvos digitālos produktos.',
    'footer.quicklinks': 'Ātrās Saites',
    'footer.connect': 'Savienojieties ar Mums',
    'footer.rights': 'Visas tiesības aizsargātas.',
    'project.back': 'Atpakaļ uz Projektiem',
    'project.client': 'Klients',
    'project.category': 'Kategorija',
    'project.overview': 'Pārskats',
    'project.goals': 'Projekta Mērķi',
    'project.process': 'Mūsu Process',
    'project.features': 'Galvenās Iezīmes',
    'project.results': 'Rezultāti',
    'project.cta.title': 'Gatavs Sākt Savu Projektu?',
    'project.cta.subtitle': 'Apspriedīsim, kā mēs varam īstenot jūsu redzējumu.',
    'project.cta.button': 'Sazināties',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('e9-lang');
    if (saved === 'lv' || saved === 'en') setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('e9-lang', lang);
  };

  const t = (key: string): string => translations[language][key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
