'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'lv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.courses': 'Courses',
    'nav.team': 'Our Team',
    'nav.contact': 'Contact',
    'hero.title': 'We create interactive digital products, AI workflows, and custom learning systems',
    'hero.subtitle': 'Transform your ideas into engaging digital experiences with our creative and technical expertise.',
    'hero.cta.consultation': 'Book a Free Consultation',
    'hero.cta.projects': 'See Our Projects',
    'problems.eyebrow': 'PROBLEMS WE SOLVE',
    'problems.title': 'Sound familiar?',
    'problems.subtitle': 'These are the conversations we have every week.',
    'problems.1': '"I have an idea but don\'t know how to build it"',
    'problems.2': '"We want to use AI but don\'t know where to start"',
    'problems.3': '"We need a custom platform, not another template"',
    'problems.4': '"Our knowledge is not structured into a product"',
    'problems.5': '"We want automation instead of manual work"',
    'results.eyebrow': 'REAL RESULTS',
    'results.title': 'What We Actually Delivered',
    'results.1.stat': '8 weeks',
    'results.1.text': 'Helped launch a SaaS platform from idea to working MVP',
    'results.2.stat': '→ Product',
    'results.2.text': 'Enabled structured startup development for early-stage founders',
    'whoweworkwith.eyebrow': 'WHO THIS IS FOR',
    'whoweworkwith.title': 'Who We Work With',
    'whoweworkwith.1.title': 'Startups',
    'whoweworkwith.1.desc': 'Building MVPs & SaaS platforms — from zero to launch, fast.',
    'whoweworkwith.2.title': 'Experts & Creators',
    'whoweworkwith.2.desc': 'Turning knowledge into premium digital products and courses.',
    'whoweworkwith.3.title': 'Companies',
    'whoweworkwith.3.desc': 'Automating workflows and operations with custom AI agents.',
    'whoweworkwith.4.title': 'Educators',
    'whoweworkwith.4.desc': 'Creating scalable, engaging online learning systems.',
    'core.eyebrow': 'WHAT WE DO BEST',
    'core.badge': 'NEW',
    'core.title': 'Our 4 Core Expertise Areas',
    'core.subtitle': 'Every project we take on falls into one or more of these areas.',
    'core.build.title': 'Veido',
    'core.build.desc': 'Web apps, SaaS platforms, and MVPs built from scratch.',
    'core.build.tag1': 'SaaS',
    'core.build.tag2': 'MVPs',
    'core.build.tag3': 'Web Apps',
    'core.automate.title': 'Automatizē',
    'core.automate.desc': 'AI agents and workflow automation that replace manual work.',
    'core.automate.tag1': 'AI',
    'core.automate.tag2': 'Agents',
    'core.automate.tag3': 'Flows',
    'core.educate.title': 'Māci',
    'core.educate.desc': 'Custom LMS platforms and gamified learning systems.',
    'core.educate.tag1': 'LMS',
    'core.educate.tag2': 'Courses',
    'core.educate.tag3': 'eLearning',
    'core.create.title': 'Radi',
    'core.create.desc': 'Interactive books, catalogues, and digital experiences.',
    'core.create.tag1': 'Interactive',
    'core.create.tag2': 'Content',
    'core.create.tag3': 'Media',
    'whatwedo.title': 'What We Do',
    'whatwedo.eyebrow': 'OUR SERVICES',
    'whatwedo.subtitle': 'From first idea to production — full-stack, end-to-end.',
    'whatwedo.saas.title': 'Web & SaaS Platform Development',
    'whatwedo.saas.desc': 'We build custom web applications and SaaS platforms tailored to your business model and goals.',
    'whatwedo.saas.tag1': 'MVP development for startups',
    'whatwedo.saas.tag2': 'Full-scale SaaS platforms',
    'whatwedo.saas.tag3': 'Dashboards, admin systems & integrations',
    'whatwedo.structure.title': 'Idea → Structured System',
    'whatwedo.structure.desc': 'We help structure your idea into a clear, executable system before development begins.',
    'whatwedo.structure.tag1': 'Idea validation and structuring',
    'whatwedo.structure.tag2': 'Feature architecture and user flows',
    'whatwedo.structure.tag3': 'Business logic and system planning',
    'whatwedo.automation.title': 'Process Automation & Integrations',
    'whatwedo.automation.desc': 'We design systems that connect your tools, data, and processes into one seamless flow.',
    'whatwedo.automation.tag1': 'Business process automation',
    'whatwedo.automation.tag2': 'CRM and internal tool integrations',
    'whatwedo.automation.tag3': 'Data flows and system connections',
    'whatwedo.interactive.title': 'Interactive Content Design',
    'whatwedo.interactive.desc': 'We craft engaging digital experiences including interactive books, catalogs, and multimedia content that captivates your audience.',
    'whatwedo.interactive.tag1': 'Interactive books & catalogues',
    'whatwedo.interactive.tag2': 'Multimedia & immersive experiences',
    'whatwedo.interactive.tag3': 'Embedded video storytelling',
    'whatwedo.ai.title': 'AI Integrations & Agents',
    'whatwedo.ai.desc': 'Leverage cutting-edge AI technology to automate workflows, enhance productivity, and create intelligent systems tailored to your needs.',
    'whatwedo.ai.tag1': 'Custom AI assistants & chatbots',
    'whatwedo.ai.tag2': 'Workflow automation agents',
    'whatwedo.ai.tag3': 'Intelligent data processing',
    'whatwedo.education.title': 'Education Systems & LMS',
    'whatwedo.education.desc': 'Design and implement comprehensive learning management systems and instructional content that drives real results.',
    'whatwedo.education.tag1': 'Custom LMS platforms',
    'whatwedo.education.tag2': 'Gamified learning paths',
    'whatwedo.education.tag3': 'Instructional content design',
    'whychooseus.title': 'Why Choose Us',
    'whychooseus.clientcentered': 'Client-Centered Approach',
    'whychooseus.creative': 'Creative Solutions',
    'whychooseus.results': 'Results-Driven',
    'whychooseus.ai': 'AI Expertise',
    'whychooseus.design': 'Modern Design',
    'whychooseus.educational': 'Educational Excellence',
    'featured.title': 'Featured Projects',
    'featured.viewall': 'View All Projects',
    'howwework.title': 'How We Work',
    'howwework.discovery': 'Discovery',
    'howwework.discovery.desc': 'We learn about your goals, challenges, and vision',
    'howwework.design': 'Design',
    'howwework.design.desc': 'Creating beautiful, user-centered solutions',
    'howwework.aiintegration': 'AI Integration',
    'howwework.aiintegration.desc': 'Implementing smart automation and workflows',
    'howwework.delivery': 'Delivery',
    'howwework.delivery.desc': 'Launching your project with comprehensive support',
    'howwework.support': 'Support',
    'howwework.support.desc': 'Ongoing maintenance and optimization',
    'testimonials.title': 'What Our Clients Say',
    'cta.title': 'Ready to Transform Your Ideas?',
    'cta.subtitle': 'Start your free consultation today and discover how we can help you achieve your goals.',
    'cta.button': 'Book Your Free Consultation',
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the talented professionals behind E9 Studija.',
    'team.whoweare': 'Who We Are',
    'team.description1': 'E9 Studija is a creative digital studio based in Latvia, specializing in interactive content design, AI integrations, and educational technology solutions.',
    'team.description2': 'Our team is passionate about innovation, collaboration, and delivering results that exceed expectations.',
    'team.description3': "Whether you're looking to create an interactive learning platform, integrate AI into your workflows, or design engaging digital content, we have the expertise to bring your vision to life.",
    'team.meetteam': 'Meet Our Team',
    'team.member1.name': 'Anna Kovaļevska',
    'team.member1.position': 'Founder & Creative Director',
    'team.member1.bio': 'With over 15 years of experience in digital design and education, Anna leads our creative vision and client strategy.',
    'team.member2.name': 'Māris Liepiņš',
    'team.member2.position': 'Lead AI Engineer',
    'team.member2.bio': 'Māris specializes in AI integrations and automation, bringing cutting-edge technology solutions to our clients.',
    'team.member3.name': 'Laura Bērziņa',
    'team.member3.position': 'UX/UI Designer',
    'team.member3.bio': 'Laura creates beautiful, intuitive interfaces that delight users and drive engagement across all platforms.',
    'team.member4.name': 'Jānis Kalniņš',
    'team.member4.position': 'Education Technology Specialist',
    'team.member4.bio': 'Jānis designs and implements comprehensive learning systems that transform educational experiences.',
    'team.worktogether': "Let's Work Together",
    'team.worktogether.subtitle': 'Ready to start your project? Get in touch with our team today.',
    'team.contactus': 'Contact Us',
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Ready to transform your ideas into reality? Book a free consultation or send us a message.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.name.placeholder': 'Your full name',
    'contact.email.placeholder': 'your@email.com',
    'contact.phone': 'Phone Number *',
    'contact.phone.placeholder': '+371 XXXXXXXX',
    'contact.message.placeholder': 'Tell us about your project...',
    'contact.send': 'Submit',
    'contact.sending': 'Sending...',
    'contact.select.time': 'Select Time Slot',
    'contact.success.title': 'Message Sent!',
    'contact.success.message': 'Your form was submitted, we will contact you!',
    'contact.error.fields': 'Please fill in all required fields',
    'contact.error.failed': 'Failed to submit form. Please try again.',
    'contact.no.slots': 'No available time slots. Please contact us directly.',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Hours',
    'contact.info.hours.text': 'Mon-Fri: 9AM - 6PM',
    'contact.info.response': 'Response Time',
    'contact.info.response.text': 'Within 24 hours',
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Explore our portfolio of innovative digital products, AI integrations, and learning systems.',
    'projects.loading': 'Loading...',
    'projects.view': 'View Project',
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Expand your skills with our expertly crafted online courses.',
    'courses.filter.all': 'All',
    'courses.filter.marketing': 'Marketing',
    'courses.filter.business': 'Business',
    'courses.filter.creativity': 'Creativity',
    'courses.filter.education': 'Education',
    'courses.filter.ai': 'AI Skills',
    'courses.filter.technology': 'Technology',
    'courses.filter.personal': 'Personal Development',
    'courses.eyebrow': 'Learn Online',
    'courses.custom.title': 'Custom Course Development',
    'courses.custom.subtitle': 'Need a custom learning solution for your organization? We design and develop tailored courses.',
    'courses.custom.button': 'Discuss Your Needs',
    'courses.search.placeholder': 'Search courses…',
    'courses.empty': 'No courses found. Check back soon!',
    'courses.back': 'Back to Courses',
    'courses.by': 'by',
    'courses.enroll.free': 'Enroll for Free',
    'courses.enroll.paid': 'Enroll Now',
    'courses.preview.hint': 'Preview lectures available before enrolling',
    'courses.feature.certificate': 'Certificate of completion',
    'courses.feature.lifetime': 'Lifetime access',
    'courses.feature.lectures': 'on-demand lectures',
    'courses.section.learn': 'What you will learn',
    'courses.section.requirements': 'Requirements',
    'courses.section.description': 'Course description',
    'courses.section.curriculum': 'Course curriculum',
    'courses.section.instructor': 'Your instructor',
    'courses.section.reviews': 'Student reviews',
    'courses.curriculum.sections': 'sections',
    'courses.curriculum.lectures': 'lectures',
    'footer.description': 'Creative and AI consulting studio specializing in interactive digital products and custom learning systems.',
    'footer.quicklinks': 'Quick Links',
    'footer.connect': 'Connect With Us',
    'footer.rights': 'All rights reserved.',
    'project.back': 'Back to Projects',
    'project.client': 'Client',
    'project.category': 'Category',
    'project.overview': 'Overview',
    'project.goals': 'Project Goals',
    'project.process': 'Our Process',
    'project.features': 'Key Features',
    'project.results': 'Results',
    'project.cta.title': 'Ready to Start Your Project?',
    'project.cta.subtitle': "Let's discuss how we can bring your vision to life.",
    'project.cta.button': 'Get in Touch',
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullname': 'Full Name',
    'auth.fullname.placeholder': 'Your full name',
    'auth.password.placeholder': 'Min. 6 characters',
    'auth.password.hint': 'Must be at least 6 characters',
    'auth.new.password': 'New Password',
    'auth.confirm.password': 'Confirm Password',
    'auth.forgot': 'Forgot password?',
    'auth.loading': 'Please wait...',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.register.link': 'Create one',
    'auth.login.link': 'Sign in',
    'auth.back.login': '← Back to login',
    'auth.login.title': 'Welcome back',
    'auth.login.subtitle': 'Sign in to your E9 Studija account',
    'auth.login.cta': 'Sign In',
    'auth.register.title': 'Create an account',
    'auth.register.subtitle': 'Join E9 Studija to start learning',
    'auth.register.cta': 'Create Account',
    'auth.register.success.title': 'Check your email',
    'auth.register.success.message': 'We sent a confirmation link. Click it to activate your account.',
    'auth.forgot.title': 'Reset your password',
    'auth.forgot.subtitle': 'Enter your email and we will send you a reset link.',
    'auth.forgot.cta': 'Send Reset Link',
    'auth.forgot.sent.title': 'Email sent!',
    'auth.forgot.sent.message': 'Check your inbox for the password reset link.',
    'auth.reset.title': 'Set new password',
    'auth.reset.subtitle': 'Choose a strong password for your account.',
    'auth.reset.cta': 'Update Password',
    'auth.error.fields': 'Please fill in all required fields',
    'auth.error.invalid': 'Invalid email or password',
    'auth.error.password.short': 'Password must be at least 6 characters',
    'auth.error.password.mismatch': 'Passwords do not match',
  },
  lv: {
    'nav.home': 'Sākums',
    'nav.projects': 'Projekti',
    'nav.courses': 'Kursi',
    'nav.team': 'Mūsu Komanda',
    'nav.contact': 'Kontakti',
    'hero.title': 'Mēs veidojam interaktīvus digitālus produktus, AI risinājumus un mācību sistēmas',
    'hero.subtitle': 'Pārveidojiet savas idejas saistošās digitālās pieredzēs ar mūsu radošo un tehnisko kompetenci.',
    'hero.cta.consultation': 'Rezervēt Bezmaksas Konsultāciju',
    'hero.cta.projects': 'Skatīt Mūsu Projektus',
    'problems.eyebrow': 'PROBLĒMAS, KO RISINĀM',
    'problems.title': 'Pazīstami?',
    'problems.subtitle': 'Šīs ir sarunas, kuras mēs dzirdam katru nedēļu.',
    'problems.1': '"Man ir ideja, bet nezinu, kā to uzbūvēt"',
    'problems.2': '"Vēlamies izmantot AI, bet nezinām, no kurienes sākt"',
    'problems.3': '"Mums nepieciešama pielāgota platforma, nevis vēl viens šablons"',
    'problems.4': '"Mūsu zināšanas nav strukturētas produktā"',
    'problems.5': '"Vēlamies automatizāciju, nevis manuālu darbu"',
    'results.eyebrow': 'REĀLI REZULTĀTI',
    'results.title': 'Ko Mēs Faktiski Paveicām',
    'results.1.stat': '8 nedēļas',
    'results.1.text': 'Palīdzējām laist SaaS platformu no idejas līdz darbojošam MVP',
    'results.2.stat': '→ Produkts',
    'results.2.text': 'Nodrošinājām strukturētu jaunuzņēmumu attīstību agrīnās stadijas dibinātājiem',
    'whoweworkwith.eyebrow': 'KAM MĒS STRĀDĀJAM',
    'whoweworkwith.title': 'Ar Ko Mēs Strādājam',
    'whoweworkwith.1.title': 'Jaunuzņēmumi',
    'whoweworkwith.1.desc': 'MVP un SaaS platformu izveide — no nulles līdz laišanai tirgū.',
    'whoweworkwith.2.title': 'Eksperti un Radītāji',
    'whoweworkwith.2.desc': 'Zināšanu pārvēršana digitālos produktos un kursos.',
    'whoweworkwith.3.title': 'Uzņēmumi',
    'whoweworkwith.3.desc': 'Darba procesu automatizācija ar pielāgotiem AI aģentiem.',
    'whoweworkwith.4.title': 'Izglītotāji',
    'whoweworkwith.4.desc': 'Mērogojamu, saistošu tiešsaistes mācību sistēmu izveide.',
    'core.eyebrow': 'KO MĒS DARĀM VISLABĀK',
    'core.badge': 'JAUNS',
    'core.title': 'Mūsu 4 galvenās kompetences',
    'core.subtitle': 'Katrs projekts, ko veidojam, ietilpst vienā vai vairākās no šīm jomām.',
    'core.build.title': 'Build',
    'core.build.desc': 'Web lietotnes, SaaS platformas un MVP, kas veidoti no nulles.',
    'core.build.tag1': 'SaaS',
    'core.build.tag2': 'MVPs',
    'core.build.tag3': 'Web Lietotnes',
    'core.automate.title': 'Automate',
    'core.automate.desc': 'AI aģenti un darba plūsmu automatizācija, kas aizstāj manuālu darbu.',
    'core.automate.tag1': 'AI',
    'core.automate.tag2': 'Aģenti',
    'core.automate.tag3': 'Plūsmas',
    'core.educate.title': 'Educate',
    'core.educate.desc': 'Pielāgotas LMS platformas un spēļotas mācību sistēmas.',
    'core.educate.tag1': 'LMS',
    'core.educate.tag2': 'Kursi',
    'core.educate.tag3': 'eLearning',
    'core.create.title': 'Create',
    'core.create.desc': 'Interaktīvas grāmatas, katalogi un digitālas pieredzes.',
    'core.create.tag1': 'Interaktīvs',
    'core.create.tag2': 'Saturs',
    'core.create.tag3': 'Mediji',
    'whatwedo.title': 'Ko Mēs Darām',
    'whatwedo.eyebrow': 'MŪSU PAKALPOJUMI',
    'whatwedo.subtitle': 'No pirmajās idejas līdz ražojumam — pilnvērtīgi, pilnu ciklu.',
    'whatwedo.saas.title': 'Web un SaaS Platformu Izstrāde',
    'whatwedo.saas.desc': 'Mēs veidojam pielāgotas tīmekļa lietojumprogrammas un SaaS platformas atbilstoši jūsu biznesa modelim.',
    'whatwedo.saas.tag1': 'MVP izstrāde jaunuzņēmumiem',
    'whatwedo.saas.tag2': 'Pilna mēroga SaaS platformas',
    'whatwedo.saas.tag3': 'Panelis, admin sistēmas un integrācijas',
    'whatwedo.structure.title': 'Ideja → Strukturēta Sistēma',
    'whatwedo.structure.desc': 'Mēs palīdzām strukturēt jūsu ideju skaidrā, izpildamā sistēmā pirms izstrādes sākuma.',
    'whatwedo.structure.tag1': 'Idejas validācija un strukturēšana',
    'whatwedo.structure.tag2': 'Funkciju arhitektūra un lietotāju plūsmas',
    'whatwedo.structure.tag3': 'Biznesa loika un sistēmas plānošana',
    'whatwedo.automation.title': 'Procesu Automatizācija un Integrācijas',
    'whatwedo.automation.desc': 'Mēs vērojam sistēmas, kas savieno jūsu rīkus, datus un procesus vienā bezrūpīgā plasmā.',
    'whatwedo.automation.tag1': 'Biznesa procesu automatizācija',
    'whatwedo.automation.tag2': 'CRM un iekšējo rīku integrācijas',
    'whatwedo.automation.tag3': 'Datu plūsmas un sistēmu savienojumi',
    'whatwedo.interactive.title': 'Interaktīva Satura Dizains',
    'whatwedo.interactive.desc': 'Mēs veidojam saistošas digitālās pieredzes, tostarp interaktīvas grāmatas, katalogus un multimedijai saturu.',
    'whatwedo.interactive.tag1': 'Interaktīvas grāmatas un katalogi',
    'whatwedo.interactive.tag2': 'Multimedijai un iegremdejošas pieredzes',
    'whatwedo.interactive.tag3': 'Ieintegrēts video stāstījums',
    'whatwedo.ai.title': 'AI Integrācijas un Aģenti',
    'whatwedo.ai.desc': 'Izmantojiet jaunāko AI tehnoloģiju, lai automatizētu darba procesus un izveidotu inteliģentas sistēmas.',
    'whatwedo.ai.tag1': 'Pielāgoti AI asistenti un čat-boti',
    'whatwedo.ai.tag2': 'Darba plūsmas automatizācijas aģenti',
    'whatwedo.ai.tag3': 'Intelektuālā datu apstrāde',
    'whatwedo.education.title': 'Izglītības Sistēmas un LMS',
    'whatwedo.education.desc': 'Projektējiet un ieviešiet visaptverošas mācību pārvaldības sistēmas un mācību saturu.',
    'whatwedo.education.tag1': 'Pielāgotas LMS platformas',
    'whatwedo.education.tag2': 'Gamificēti mācību ceļi',
    'whatwedo.education.tag3': 'Mācību satura dizains',
    'whychooseus.title': 'Kāpēc Izvēlēties Mūs',
    'whychooseus.clientcentered': 'Klienta Centrēta Pieeja',
    'whychooseus.creative': 'Radoši Risinājumi',
    'whychooseus.results': 'Rezultātu Orientēti',
    'whychooseus.ai': 'AI Ekspertīze',
    'whychooseus.design': 'Moderns Dizains',
    'whychooseus.educational': 'Izglītības Izcilība',
    'featured.title': 'Izceltie Projekti',
    'featured.viewall': 'Skatīt Visus Projektus',
    'howwework.title': 'Kā Mēs Strādājam',
    'howwework.discovery': 'Izpēte',
    'howwework.discovery.desc': 'Mēs uzzinām par jūsu mērķiem, izaicinājumiem un redzējumu',
    'howwework.design': 'Dizains',
    'howwework.design.desc': 'Veidojam skaistu, lietotājam centrētu risinājumu',
    'howwework.aiintegration': 'AI Integrācija',
    'howwework.aiintegration.desc': 'Ieviešam inteliģentu automatizāciju un darba procesus',
    'howwework.delivery': 'Piegāde',
    'howwework.delivery.desc': 'Palaidām jūsu projektu ar visaptverošu atbalstu',
    'howwework.support': 'Atbalsts',
    'howwework.support.desc': 'Nepārtraukta uzturēšana un optimizācija',
    'testimonials.title': 'Ko Saka Mūsu Klienti',
    'cta.title': 'Gatavs Pārveidot Savas Idejas?',
    'cta.subtitle': 'Sāciet savu bezmaksas konsultāciju šodien.',
    'cta.button': 'Rezervēt Bezmaksas Konsultāciju',
    'team.title': 'Mūsu Komanda',
    'team.subtitle': 'Iepazīstieties ar talantīgajiem profesionāļiem E9 Studija pamatā.',
    'team.whoweare': 'Kas Mēs Esam',
    'team.description1': 'E9 Studija ir radoša digitālā studija Latvijā, kas specializējas interaktīvā satura dizainā, AI integrācijās un izglītības tehnoloģiju risinājumos.',
    'team.description2': 'Mūsu komanda ir aizrautīga ar inovācijām, sadarbību un rezultātu sniegšanu.',
    'team.description3': 'Neatkarīgi no tā, vai vēlaties izveidot interaktīvu mācību platformu vai integrēt AI savos darba procesos, mēs esam šeit.',
    'team.meetteam': 'Iepazīstieties ar Mūsu Komandu',
    'team.member1.name': 'Anna Kovaļevska',
    'team.member1.position': 'Dibinātāja un Radošā Direktore',
    'team.member1.bio': 'Ar vairāk nekā 15 gadu pieredzi digitālajā dizainā un izglītībā, Anna vada mūsu radošo vīziju.',
    'team.member2.name': 'Māris Liepiņš',
    'team.member2.position': 'Galvenais AI Inženieris',
    'team.member2.bio': 'Māris specializējas AI integrācijās un automatizācijā.',
    'team.member3.name': 'Laura Bērziņa',
    'team.member3.position': 'UX/UI Dizainere',
    'team.member3.bio': 'Laura rada skaistu, intuitīvu saskarni.',
    'team.member4.name': 'Jānis Kalniņš',
    'team.member4.position': 'Izglītības Tehnoloģiju Speciālists',
    'team.member4.bio': 'Jānis projektē un ievieš visaptverošas mācību sistēmas.',
    'team.worktogether': 'Strādāsim Kopā',
    'team.worktogether.subtitle': 'Gatavs sākt savu projektu? Sazinieties ar mūsu komandu.',
    'team.contactus': 'Sazināties ar Mums',
    'contact.title': 'Sazinies ar Mums',
    'contact.subtitle': 'Gatavs pārveidot savas idejas realitātē? Rezervē bezmaksas konsultāciju.',
    'contact.name': 'Vārds',
    'contact.email': 'E-pasts',
    'contact.message': 'Ziņojums',
    'contact.name.placeholder': 'Tavs pilnais vārds',
    'contact.email.placeholder': 'tavs@epasts.lv',
    'contact.phone': 'Telefona numurs *',
    'contact.phone.placeholder': '+371 XXXXXXXX',
    'contact.message.placeholder': 'Pastāsti mums par savu projektu...',
    'contact.send': 'Iesniegt',
    'contact.sending': 'Sūta...',
    'contact.select.time': 'Izvēlies Laiku',
    'contact.success.title': 'Ziņa Nosūtīta!',
    'contact.success.message': 'Paldies, anketa ir iesniegta! Mēs ar jums sazināsimies!',
    'contact.error.fields': 'Lūdzu, aizpildi visus obligātos laukus',
    'contact.error.failed': 'Neizdevās nosūtīt formu. Lūdzu, mēģini vēlreiz.',
    'contact.no.slots': 'Pašlaik nav pieejamu laika slotu.',
    'contact.info.email': 'E-pasts',
    'contact.info.hours': 'Darba Laiks',
    'contact.info.hours.text': 'P-Pk: 9:00 - 18:00',
    'contact.info.response': 'Atbildes Laiks',
    'contact.info.response.text': 'Līdz 24 stundām',
    'projects.title': 'Mūsu Projekti',
    'projects.subtitle': 'Iepazīstieties ar mūsu inovatīvu digitālo produktu portfeli.',
    'projects.loading': 'Ielādē...',
    'projects.view': 'Skatīt Projektu',
    'courses.title': 'Mūsu Kursi',
    'courses.subtitle': 'Paplašiniet savas prasmes ar mūsu ekspertu veidotajiem tiešsaistes kursiem.',
    'courses.filter.all': 'Visi',
    'courses.filter.marketing': 'Mārketings',
    'courses.filter.business': 'Bizness',
    'courses.filter.creativity': 'Radošums',
    'courses.filter.education': 'Izglītība',
    'courses.filter.ai': 'AI Prasmes',
    'courses.filter.technology': 'Tehnoloģijas',
    'courses.filter.personal': 'Personīga Izaugsme',
    'courses.eyebrow': 'Mācies Tiešsaistē',
    'courses.custom.title': 'Individuālu Kursu Izstrāde',
    'courses.custom.subtitle': 'Vai jums nepieciešams individuāls mācību risinājums?',
    'courses.custom.button': 'Apspriežam Jūsu Vajadzības',
    'courses.search.placeholder': 'Meklēt kursus…',
    'courses.empty': 'Kursi nav atrasti. Ieskaties drīzumā!',
    'courses.back': 'Atpakaļ uz Kursiem',
    'courses.by': 'autors',
    'courses.enroll.free': 'Reģistrēties Bez Maksas',
    'courses.enroll.paid': 'Reģistrēties',
    'courses.preview.hint': 'Priekšskatījuma lekcijas pieejamas pirms reģistrācijas',
    'courses.feature.certificate': 'Pabeigšanas sertifikāts',
    'courses.feature.lifetime': 'Mūža piekļuve',
    'courses.feature.lectures': 'lekcijas pēc pieprasījuma',
    'courses.section.learn': 'Ko tu iemācīsies',
    'courses.section.requirements': 'Prasības',
    'courses.section.description': 'Kursa apraksts',
    'courses.section.curriculum': 'Kursa programma',
    'courses.section.instructor': 'Tavs pasniedzējs',
    'courses.section.reviews': 'Studentu atsauksmes',
    'courses.curriculum.sections': 'nodaļas',
    'courses.curriculum.lectures': 'lekcijas',
    'footer.description': 'Radošā un AI konsultēšanas studija, kas specializējas interaktīvos digitālos produktos.',
    'footer.quicklinks': 'Ātrās Saites',
    'footer.connect': 'Savienojieties ar Mums',
    'footer.rights': 'Visas tiesības aizsargātas.',
    'project.back': 'Atpakaļ uz Projektiem',
    'project.client': 'Klients',
    'project.category': 'Kategorija',
    'project.overview': 'Pārskats',
    'project.goals': 'Projekta Mērķi',
    'project.process': 'Mūsu Process',
    'project.features': 'Galvenās Iezīmes',
    'project.results': 'Rezultāti',
    'project.cta.title': 'Gatavs Sākt Savu Projektu?',
    'project.cta.subtitle': 'Apspriedīsim, kā mēs varam īstenot jūsu redzējumu.',
    'project.cta.button': 'Sazināties',
    // Auth
    'auth.email': 'E-pasts',
    'auth.password': 'Parole',
    'auth.fullname': 'Pilnais vārds',
    'auth.fullname.placeholder': 'Tavs pilnais vārds',
    'auth.password.placeholder': 'Vismaz 6 simboli',
    'auth.password.hint': 'Vismaz 6 simboli',
    'auth.new.password': 'Jaunā parole',
    'auth.confirm.password': 'Apstipriniet paroli',
    'auth.forgot': 'Aizmirsi paroli?',
    'auth.loading': 'Lūdzu uzgaidiet...',
    'auth.no.account': 'Nav konta?',
    'auth.have.account': 'Jau ir konts?',
    'auth.register.link': 'Izveidot',
    'auth.login.link': 'Ielogoties',
    'auth.back.login': '← Atpakaļ uz ienākšanu',
    'auth.login.title': 'Laipni lūdzam',
    'auth.login.subtitle': 'Ielogojies savā E9 Studija kontā',
    'auth.login.cta': 'Ielogoties',
    'auth.register.title': 'Izveidot kontu',
    'auth.register.subtitle': 'Pievienojies E9 Studija, lai sāktu mācīties',
    'auth.register.cta': 'Izveidot kontu',
    'auth.register.success.title': 'Pārbaudi e-pastu',
    'auth.register.success.message': 'Mēs nosūtījām apstiprinājuma saiti. Noklikšķini, lai aktivizētu kontu.',
    'auth.forgot.title': 'Atjaunot paroli',
    'auth.forgot.subtitle': 'Ievadi e-pastu un mēs nosūtīsim paroles atjaunošanas saiti.',
    'auth.forgot.cta': 'Nosūtīt saiti',
    'auth.forgot.sent.title': 'E-pasts nosūtīts!',
    'auth.forgot.sent.message': 'Pārbaudi iesūtni paroles atjaunošanas saitei.',
    'auth.reset.title': 'Iestatīt jaunu paroli',
    'auth.reset.subtitle': 'Izvēlies drošu paroli savam kontam.',
    'auth.reset.cta': 'Atjaunināt paroli',
    'auth.error.fields': 'Lūdzu aizpildi visus obligātos laukus',
    'auth.error.invalid': 'Nepareizs e-pasts vai parole',
    'auth.error.password.short': 'Parolei jābūt vismaz 6 simboliem',
    'auth.error.password.mismatch': 'Paroles nesakrīt',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('e9-lang');
    if (saved === 'lv' || saved === 'en') setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('e9-lang', lang);
  };

  const t = (key: string): string => translations[language][key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
